# SFTP pipeline

# Default Docker image provided by Atlassian (Ubuntu 16.04).
# https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/
#image: atlassian/default-image:2

# My custom public Docker image hosted at https://hub.docker.com/r/baizmandesign/bbsftp
image: baizmandesign/bbsftp:1.0

pipelines:
  default:
    - step:
        name: publish to 826 boston
        deployment: production__826-boston
        script:
          # exclude bitbucket-pipelines.yml and .git from being copied to the remote host
          - rm -rf bitbucket-pipelines.yml .git README.md
          - pipe: atlassian/sftp-deploy:0.5.6
            variables:
              USER: $BOS_SFTP_USER
              SERVER: $FLYWHEEL_SFTP_HOST
              REMOTE_PATH: $BOS_REMOTE_PATH
              LOCAL_PATH: $LOCAL_PATH
              PASSWORD: $BOS_SFTP_PASSWORD
        # https://bitbucket.org/product/features/pipelines/integrations?p=atlassian/email-notify
        after-script:
          - pipe: atlassian/email-notify:0.3.12
            variables:
              USERNAME: $BD_BB_SERVICE_ACCOUNT_EMAIL
              PASSWORD: $BD_BB_SERVICE_ACCOUNT_PASSWORD
              FROM: $BD_BB_SERVICE_ACCOUNT_EMAIL
              TO: $PIPELINE_NOTIFICATION_RECIPIENT
              HOST: $PIPELINE_NOTIFICATION_SMTP_HOST
              PORT: $PIPELINE_NOTIFICATION_SMTP_PORT
              # can we add variables in this?
              SUBJECT: 'Bitbucket SFTP deployment to 826boston.org'
              BODY_PLAIN: 'The update to $BITBUCKET_REPO_FULL_NAME was successfully deployed to the 826 Boston website on Flywheel.'
    - step:
        name: publish to pce
        deployment: production__pce
        script:
          # exclude bitbucket-pipelines.yml and .git from being copied to the remote host
          - rm -rf bitbucket-pipelines.yml .git README.md
          - pipe: atlassian/sftp-deploy:0.5.6
            variables:
              USER: $PCE_SFTP_USER
              SERVER: $FLYWHEEL_SFTP_HOST
              REMOTE_PATH: $PCE_REMOTE_PATH
              LOCAL_PATH: $LOCAL_PATH
              PASSWORD: $PCE_SFTP_PASSWORD
        # https://bitbucket.org/product/features/pipelines/integrations?p=atlassian/email-notify
        after-script:
          - pipe: atlassian/email-notify:0.3.12
            variables:
              USERNAME: $BD_BB_SERVICE_ACCOUNT_EMAIL
              PASSWORD: $BD_BB_SERVICE_ACCOUNT_PASSWORD
              FROM: $BD_BB_SERVICE_ACCOUNT_EMAIL
              TO: $PIPELINE_NOTIFICATION_RECIPIENT
              HOST: $PIPELINE_NOTIFICATION_SMTP_HOST
              PORT: $PIPELINE_NOTIFICATION_SMTP_PORT
              # can we add variables in this?
              SUBJECT: 'Bitbucket SFTP deployment to pce.massart.edu'
              BODY_PLAIN: 'The update to $BITBUCKET_REPO_FULL_NAME was successfully deployed to the PCE catalog website on Flywheel.'
