# create a zip archive (without bitbucket-pipelines.yml) and copy it to wp.baizmandesign.com.
# $BDSL_TARGET_ZIP_FILENAME is defined in a repository variable.

pipelines:
  default:
    - step:
        name: Deploy ZIP to wp.baizmandesign.com.
        script:
          - git archive -o $BDSL_TARGET_ZIP_FILENAME -9 --prefix=$BDSL_PLUGIN_SLUG/ HEAD
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $BDSL_SSH_USER
              SERVER: $BDSL_SSH_HOST
              REMOTE_PATH: $BDSL_SSH_HOST_SUBDIR
              LOCAL_PATH: $BDSL_TARGET_ZIP_FILENAME
